# Generated by Skyramp v1.3.16 on 2026-03-31 07:41:56.495591204 +0000 UTC m=+127.863130859
# Command: skyramp generate contract rest http://localhost:8000/orders/{order_id} \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output contract_patch_orders_404_test.py \
# 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/backend/tests/python \
# 		--overwrite \
# 		--path-params order_id=99999 \
# 		--request-data {"customer_email":"updated@mail.com","status":"confirmed"} \
# 		--response-status-code 404 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /orders/{order_id} PATCH
def test_orders_order_id_2_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    order_id = "99999"

    # Request Body
    orders_order_id_2_PATCH_request_body = r'''{
        "customer_email": "updated@mail.com",
        "status": "confirmed"
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="PATCH",
        status_code=404,
        request_body=orders_order_id_2_PATCH_request_body
    )
    client.apply_mock(mock)

    # Execute Request
    orders_order_id_2_PATCH_response = client.send_request(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="PATCH",
        body=orders_order_id_2_PATCH_request_body,
        headers=headers,
        path_params={"order_id": order_id}
    )

    # Generated Assertions
    assert orders_order_id_2_PATCH_response.status_code == 404
    assert skyramp.get_response_value(orders_order_id_2_PATCH_response, "detail") is not None

    client.remove_all_mocks()


if __name__ == "__main__":
    test_orders_order_id_2_patch()
