# Generated by Skyramp v1.3.16 on 2026-03-31 07:42:32.280485032 +0000 UTC m=+163.648024687
# Command: skyramp generate contract rest http://localhost:8000/api/v1/orders/{order_id} \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output contract_patch_orders_200_test.py \
# 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/backend/tests/python \
# 		--overwrite \
# 		--path-params order_id=1 \
# 		--request-data {"customer_email":"updated@mail.com","status":"confirmed","items":[{"product_id":1,"quantity":2}],"discount_type":"percentage","discount_value":10.0} \
# 		--response-data {"order_id":1,"customer_email":"updated@mail.com","status":"confirmed","total_amount":19.98,"discount_type":"percentage","discount_value":10.0,"discount_amount":1.998,"items":[{"order_item_id":1,"product_id":1,"quantity":2}],"created_at":"2022-01-01T00:00:00","updated_at":"2022-01-01T00:00:00"} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/orders/{order_id} PATCH
def test_v_1_orders_order_id_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    order_id = "1"

    # Request Body
    v1_orders_order_id_PATCH_request_body = r'''{
        "customer_email": "updated@mail.com",
        "discount_type": "percentage",
        "discount_value": 10,
        "items": [
            {
                "product_id": 1,
                "quantity": 2
            }
        ],
        "status": "confirmed"
    }'''

    # Expected Response Body
    expected_v1_orders_order_id_PATCH_response_body = r'''{
        "created_at": "2022-01-01T00:00:00",
        "customer_email": "updated@mail.com",
        "discount_amount": 1.998,
        "discount_type": "percentage",
        "discount_value": 10,
        "items": [
            {
                "order_item_id": 1,
                "product_id": 1,
                "quantity": 2
            }
        ],
        "order_id": 1,
        "status": "confirmed",
        "total_amount": 19.98,
        "updated_at": "2022-01-01T00:00:00"
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="PATCH",
        status_code=200,
        request_body=v1_orders_order_id_PATCH_request_body,
        response_body=expected_v1_orders_order_id_PATCH_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    v1_orders_order_id_PATCH_response = client.send_request(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="PATCH",
        body=v1_orders_order_id_PATCH_request_body,
        headers=headers,
        path_params={"order_id": order_id}
    )

    # Generated Assertions
    assert v1_orders_order_id_PATCH_response.status_code == 200
    assert skyramp.check_schema(v1_orders_order_id_PATCH_response, expected_v1_orders_order_id_PATCH_response_body)
    assert skyramp.get_response_value(v1_orders_order_id_PATCH_response, "created_at") is not None
    assert skyramp.get_response_value(v1_orders_order_id_PATCH_response, "customer_email") == "updated@mail.com"
    assert skyramp.get_response_value(v1_orders_order_id_PATCH_response, "status") == "confirmed"
    assert skyramp.get_response_value(v1_orders_order_id_PATCH_response, "discount_type") == "percentage"
    assert skyramp.get_response_value(v1_orders_order_id_PATCH_response, "discount_value") == 10.0
    assert skyramp.get_response_value(v1_orders_order_id_PATCH_response, "discount_amount") is not None
    assert skyramp.get_response_value(v1_orders_order_id_PATCH_response, "total_amount") is not None
    assert skyramp.get_response_value(v1_orders_order_id_PATCH_response, "discount_amount") == skyramp.get_response_value(v1_orders_order_id_PATCH_response, "total_amount") * 10.0 / 100

    client.remove_all_mocks()


if __name__ == "__main__":
    test_v_1_orders_order_id_patch()
