# Generated by Skyramp v1.3.16 on 2026-03-30 23:12:06.188266876 +0000 UTC m=+189.510883388
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/backend/tests/python \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/backend/tests/python/scenario_orders-patch-discount-calculation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    products_POST_request_body = r'''{
        "category": "Toys ",
        "description": "Soft toy bear ",
        "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
        "in_stock": true,
        "name": "bigbear ",
        "price": 20
    }'''

    # Execute Request
    products_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/products",
        method="POST",
        body=products_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert products_POST_response.status_code == 201
    assert skyramp.get_response_value(products_POST_response, "product_id") is not None
    assert skyramp.get_response_value(products_POST_response, "name") == "bigbear "
    assert skyramp.get_response_value(products_POST_response, "price") >= 0

    # Request Body
    orders_POST_request_body = r'''{
        "customer_email": "test@mail.com",
        "items": [
            {
                "product_id": 1,
                "quantity": 2
            }
        ]
    }'''

    # Execute Request
    orders_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/orders",
        method="POST",
        body=orders_POST_request_body,
        headers=headers,
        data_override={"items.0.product_id": skyramp.get_response_value(products_POST_response, "product_id")}
    )
    # Generated Assertions
    assert orders_POST_response.status_code == 201
    assert skyramp.get_response_value(orders_POST_response, "order_id") is not None
    assert skyramp.get_response_value(orders_POST_response, "customer_email") == "test@mail.com"
    assert skyramp.get_response_value(orders_POST_response, "status") == "pending"
    assert skyramp.get_response_value(orders_POST_response, "total_amount") >= 0

    # Request Body
    orders_orders_PATCH_request_body = r'''{
        "customer_email": "updated@mail.com",
        "discount_type": "percentage",
        "discount_value": 10,
        "status": "confirmed"
    }'''

    # Execute Request
    orders_orders_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/orders/{order_id}",
        method="PATCH",
        body=orders_orders_PATCH_request_body,
        headers=headers,
        path_params={"order_id": skyramp.get_response_value(orders_POST_response, "order_id")}
    )
    # Generated Assertions
    assert orders_orders_PATCH_response.status_code == 200
    assert skyramp.get_response_value(orders_orders_PATCH_response, "order_id") is not None
    assert skyramp.get_response_value(orders_orders_PATCH_response, "customer_email") == "updated@mail.com"
    assert skyramp.get_response_value(orders_orders_PATCH_response, "status") == "confirmed"
    assert skyramp.get_response_value(orders_orders_PATCH_response, "discount_type") == "percentage"
    assert skyramp.get_response_value(orders_orders_PATCH_response, "discount_value") == 10.0
    assert skyramp.get_response_value(orders_orders_PATCH_response, "discount_amount") == skyramp.get_response_value(orders_orders_PATCH_response, "total_amount") * (skyramp.get_response_value(orders_orders_PATCH_response, "discount_value") / 100)

    # Execute Request
    orders_orders_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/orders/{order_id}",
        method="GET",
        headers=headers,
        path_params={"order_id": skyramp.get_response_value(orders_POST_response, "order_id")}
    )
    # Generated Assertions
    assert orders_orders_GET_response.status_code == 200
    assert skyramp.get_response_value(orders_orders_GET_response, "order_id") == skyramp.get_response_value(orders_POST_response, "order_id")
    assert skyramp.get_response_value(orders_orders_GET_response, "customer_email") == "updated@mail.com"
    assert skyramp.get_response_value(orders_orders_GET_response, "discount_amount") == skyramp.get_response_value(orders_orders_PATCH_response, "total_amount") * (skyramp.get_response_value(orders_orders_PATCH_response, "discount_value") / 100)


if __name__ == "__main__":
    test_integration()
