# Generated by Skyramp v1.3.16 on 2026-03-31 09:57:50.789727435 +0000 UTC m=+403.841539771
# Command: skyramp generate contract rest http://localhost:8000/api/v1/orders/{order_id} \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output orders_patch_404_contract_test.py \
# 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/backend/tests/python \
# 		--overwrite \
# 		--path-params order_id=99999 \
# 		--request-data {"customer_email":"test@example.com","status":"confirmed","items":[{"product_id":1,"quantity":1}]} \
# 		--response-status-code 404 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/orders/{order_id} PATCH
def test_v_1_orders_order_id_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    order_id = "99999"

    # Request Body
    v1_orders_order_id_PATCH_request_body = r'''{
        "customer_email": "test@example.com",
        "items": [
            {
                "product_id": 1,
                "quantity": 1
            }
        ],
        "status": "confirmed"
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="PATCH",
        status_code=404,
        request_body=v1_orders_order_id_PATCH_request_body
    )
    client.apply_mock(mock)

    # Execute Request
    v1_orders_order_id_PATCH_response = client.send_request(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="PATCH",
        body=v1_orders_order_id_PATCH_request_body,
        headers=headers,
        path_params={"order_id": order_id}
    )

    # Generated Assertions
    assert v1_orders_order_id_PATCH_response.status_code == 404

    client.remove_all_mocks()


if __name__ == "__main__":
    test_v_1_orders_order_id_patch()
