# Generated by Skyramp v1.3.16 on 2026-03-30 17:38:19.767222539 +0000 UTC m=+178.617913148
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output order_discount_integration_test.py \
# 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/backend/tests/python \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/backend/tests/python/scenario_order-discount-calculation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    products_POST_request_body = r'''{
        "category": "Test",
        "description": "A test product",
        "image_url": "https://example.com/img.jpg",
        "in_stock": true,
        "name": "Test Product",
        "price": 100
    }'''
    
    # Execute Request
    products_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/products",
        method="POST",
        body=products_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert products_POST_response.status_code == 201
    assert skyramp.get_response_value(products_POST_response, "product_id") is not None
    assert skyramp.get_response_value(products_POST_response, "name") == "Test Product"
    assert skyramp.get_response_value(products_POST_response, "price") >= 0

    # Request Body
    orders_POST_request_body = r'''{
        "customer_email": "test@example.com",
        "items": [
            {
                "product_id": 1,
                "quantity": 2
            }
        ]
    }'''
    
    # Execute Request
    orders_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/orders",
        method="POST",
        body=orders_POST_request_body,
        headers=headers,
        data_override={"items.0.product_id": skyramp.get_response_value(products_POST_response, "product_id")}
    )
    # Generated Assertions
    assert orders_POST_response.status_code == 201
    assert skyramp.get_response_value(orders_POST_response, "order_id") is not None
    assert skyramp.get_response_value(orders_POST_response, "customer_email") == "test@example.com"
    assert skyramp.get_response_value(orders_POST_response, "status") == "pending"
    assert skyramp.get_response_value(orders_POST_response, "total_amount") >= 0

    # Request Body
    orders_orders_PATCH_request_body = r'''{
        "discount_type": "percentage",
        "discount_value": 10
    }'''
    
    # Execute Request
    orders_orders_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/orders/{orders}",
        method="PATCH",
        body=orders_orders_PATCH_request_body,
        headers=headers,
        path_params={"orders": skyramp.get_response_value(orders_POST_response, "order_id")}
    )
    # Generated Assertions
    assert orders_orders_PATCH_response.status_code == 200
    assert skyramp.get_response_value(orders_orders_PATCH_response, "discount_type") == "percentage"
    assert skyramp.get_response_value(orders_orders_PATCH_response, "discount_value") == 10.0
    assert skyramp.get_response_value(orders_orders_PATCH_response, "discount_amount") is not None
    assert skyramp.get_response_value(orders_orders_PATCH_response, "discount_amount") == 20.0

    # Execute Request
    orders_orders_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/orders/{orders}",
        method="GET",
        headers=headers,
        path_params={"orders": skyramp.get_response_value(orders_POST_response, "order_id")}
    )
    # Generated Assertions
    assert orders_orders_GET_response.status_code == 200
    assert skyramp.get_response_value(orders_orders_GET_response, "discount_type") == "percentage"
    assert skyramp.get_response_value(orders_orders_GET_response, "discount_amount") is not None
    assert skyramp.get_response_value(orders_orders_GET_response, "order_id") == skyramp.get_response_value(orders_POST_response, "order_id")


if __name__ == "__main__":
    test_integration()
