# Generated by Skyramp v1.3.16 on 2026-03-30 19:25:59.42948 -0700 PDT m=+0.543393334
# Command: skyramp generate contract rest http://localhost:8000/api/v1/orders \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-type Bearer \
# 		--docker-network demoshop-fullstack_demoshop-network \
# 		--framework pytest \
# 		--language python \
# 		--output-dir /Users/mrugeshmaster/git/letsramp/demoshop-fullstack/backend/tests \
# 		--overwrite \
# 		--provider \
# 		--provider-output orders_contract_test.py \
# 		--runtime docker

# Import of required libraries
import skyramp
import os
import time
import pytest


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def get_header():
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")
    return headers


# contract test for /api/v1/orders POST
def test_orders_post():
    # Invocation of Skyramp Client
    client = skyramp.Client(
        runtime="docker",
        docker_network="demoshop-fullstack_demoshop-network",
        docker_skyramp_port=35142
    )
    # Definition of authentication header
    headers = get_header()

    # Request Body
    orders_POST_request_body = r'''{
        "customer_email": "abc@mail.com",
        "items": [
            {
                "product_id": 1,
                "quantity": 2
            }
        ]
    }'''

    # Expected Response Body
    expected_orders_POST_response_body = r'''{
        "created_at": "2022-01-01T00:00:00",
        "customer_email": "abc@mail.com",
        "items": [
            {
                "order_item_id": 1,
                "product_id": 1,
                "quantity": 2
            }
        ],
        "order_id": 1,
        "status": "pending",
        "total_amount": 19.98,
        "updated_at": "2022-01-01T00:00:00"
    }'''

    # Execute Request
    orders_POST_response = client.send_request(
        url=URL,
        path="/api/v1/orders",
        method="POST",
        body=orders_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert orders_POST_response.status_code == 201
    assert skyramp.check_schema(orders_POST_response, expected_orders_POST_response_body)
    assert skyramp.get_response_value(orders_POST_response, "created_at") is not None
    assert skyramp.get_response_value(orders_POST_response, "customer_email") is not None
    assert skyramp.get_response_value(orders_POST_response, "items.0.order_item_id") is not None


# contract test for /api/v1/orders GET
def test_orders_get():
    # Invocation of Skyramp Client
    client = skyramp.Client(
        runtime="docker",
        docker_network="demoshop-fullstack_demoshop-network",
        docker_skyramp_port=35142
    )
    # Definition of authentication header
    headers = get_header()

    # Expected Response Body
    expected_orders_GET_response_body = r'''[
        {
            "created_at": "2022-01-01T00:00:00",
            "customer_email": "abc@mail.com",
            "items": [
                {
                    "order_item_id": 1,
                    "product_id": 1,
                    "quantity": 2
                }
            ],
            "order_id": 1,
            "status": "pending",
            "total_amount": 19.98,
            "updated_at": "2022-01-01T00:00:00"
        }
    ]'''

    # Execute Request
    orders_GET_response = client.send_request(
        url=URL,
        path="/api/v1/orders",
        method="GET",
        headers=headers,
        query_params={
            "limit": 10,
            "offset": 0,
            "order": "asc",
            "orderBy": None
        }
    )

    # Generated Assertions
    assert orders_GET_response.status_code == 200
    assert skyramp.check_schema(orders_GET_response, expected_orders_GET_response_body)
    assert skyramp.get_response_value(orders_GET_response, "0.created_at") is not None
    assert skyramp.get_response_value(orders_GET_response, "0.customer_email") is not None
    assert skyramp.get_response_value(orders_GET_response, "0.items.0.order_item_id") is not None


# contract test for /api/v1/orders/{order_id} GET
def test_orders_order_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client(
        runtime="docker",
        docker_network="demoshop-fullstack_demoshop-network",
        docker_skyramp_port=35142
    )
    # Definition of authentication header
    headers = get_header()

    # Declaration of variables
    order_id = 1

    # Expected Response Body
    expected_orders_order_id_GET_response_body = r'''{
        "created_at": "2022-01-01T00:00:00",
        "customer_email": "abc@mail.com",
        "items": [
            {
                "order_item_id": 1,
                "product_id": 1,
                "quantity": 2
            }
        ],
        "order_id": 1,
        "status": "pending",
        "total_amount": 19.98,
        "updated_at": "2022-01-01T00:00:00"
    }'''

    # Execute Request
    orders_order_id_GET_response = client.send_request(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="GET",
        headers=headers,
        path_params={"order_id": order_id}
    )

    # Generated Assertions
    assert orders_order_id_GET_response.status_code == 200
    assert skyramp.check_schema(orders_order_id_GET_response, expected_orders_order_id_GET_response_body)
    assert skyramp.get_response_value(orders_order_id_GET_response, "created_at") is not None
    assert skyramp.get_response_value(orders_order_id_GET_response, "customer_email") is not None
    assert skyramp.get_response_value(orders_order_id_GET_response, "items.0.order_item_id") is not None


# contract test for /api/v1/orders/{order_id} DELETE
def test_orders_order_id_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client(
        runtime="docker",
        docker_network="demoshop-fullstack_demoshop-network",
        docker_skyramp_port=35142
    )
    # Definition of authentication header
    headers = get_header()

    # Declaration of variables
    order_id = 1

    # Expected Response Body
    expected_orders_order_id_DELETE_response_body = r'''{
        "message": "Order cancelled successfully"
    }'''

    # Execute Request
    orders_order_id_DELETE_response = client.send_request(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="DELETE",
        headers=headers,
        path_params={"order_id": order_id}
    )

    # Generated Assertions
    assert orders_order_id_DELETE_response.status_code == 200
    assert skyramp.check_schema(orders_order_id_DELETE_response, expected_orders_order_id_DELETE_response_body)
    assert skyramp.get_response_value(orders_order_id_DELETE_response, "message") is not None


# contract test for /api/v1/orders/{order_id} PATCH
def test_orders_order_id_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client(
        runtime="docker",
        docker_network="demoshop-fullstack_demoshop-network",
        docker_skyramp_port=35142
    )
    # Definition of authentication header
    headers = get_header()

    # Declaration of variables
    order_id = 1

    # Request Body
    orders_order_id_PATCH_request_body = r'''{
        "customer_email": "patched@example.com",
        "discount_type": "percentage",
        "discount_value": 10,
        "items": [
            {
                "product_id": 1,
                "quantity": 2
            }
        ],
        "status": "confirmed"
    }'''

    # Expected Response Body
    expected_orders_order_id_PATCH_response_body = r'''{
        "created_at": "2022-01-01T00:00:00",
        "customer_email": "patched@example.com",
        "discount_amount": 3.996,
        "discount_type": "percentage",
        "discount_value": 10,
        "items": [
            {
                "order_item_id": 1,
                "product_id": 1,
                "quantity": 2
            }
        ],
        "order_id": 1,
        "status": "confirmed",
        "total_amount": 19.98,
        "updated_at": "2022-01-01T00:00:00"
    }'''

    # Execute Request
    orders_order_id_PATCH_response = client.send_request(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="PATCH",
        body=orders_order_id_PATCH_request_body,
        headers=headers,
        path_params={"order_id": order_id}
    )

    # Generated Assertions
    assert orders_order_id_PATCH_response.status_code == 200
    assert skyramp.check_schema(orders_order_id_PATCH_response, expected_orders_order_id_PATCH_response_body)
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "order_id") is not None
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "customer_email") == "patched@example.com"
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "status") == "confirmed"
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "discount_type") == "percentage"
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "discount_value") == 10
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "discount_amount") is not None
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "discount_amount") == pytest.approx(skyramp.get_response_value(orders_order_id_PATCH_response, "total_amount") * skyramp.get_response_value(orders_order_id_PATCH_response, "discount_value") / 100, rel=1e-5)
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "items.0.product_id") == 1
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "items.0.quantity") == 2
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "items.1.product_id") is None
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "updated_at") is not None


if __name__ == "__main__":
    test_orders_post()
    test_orders_get()
    test_orders_order_id_get()
    test_orders_order_id_delete()
    test_orders_order_id_patch()
