# Generated by Skyramp v1.3.16 on 2026-03-30 19:27:40.934741 -0700 PDT m=+0.490034710
# Command: skyramp generate integration rest http://localhost:8000/api/v1/orders \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--docker-network demoshop-fullstack_demoshop-network \
# 		--framework pytest \
# 		--language python \
# 		--output orders_integration_test.py \
# 		--output-dir /Users/mrugeshmaster/git/letsramp/demoshop-fullstack/backend/tests/python \
# 		--overwrite \
# 		--runtime docker

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client(
        runtime="docker",
        docker_network="demoshop-fullstack_demoshop-network",
        docker_skyramp_port=35142
    )
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    orders_POST_request_body = r'''{
            "customer_email": "abc@mail.com",
            "items": [{
                "product_id": 1,
                "quantity": 2
            }]
        }'''
    
    # Execute Request
    orders_POST_response = client.send_request(
        url=URL,
        path="/api/v1/orders",
        method="POST",
        body=orders_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert orders_POST_response.status_code == 201

    max_retries = 10
    sleep_time = 5
    for idx in range(max_retries):
        # Execute Request
        orders_order_id_GET_response = client.send_request(
            url=URL,
            path="/api/v1/orders/{order_id}",
            method="GET",
            headers=headers,
            path_params={"order_id": skyramp.get_response_value(orders_POST_response, "order_id")}
        )
        if orders_order_id_GET_response.status_code == 200:
            break
        time.sleep(sleep_time)


    # Request Body for PATCH (update items, status, and discount)
    orders_order_id_PATCH_request_body = r'''{
            "customer_email": "updated@mail.com",
            "status": "confirmed",
            "items": [{
                "product_id": 1,
                "quantity": 3
            }],
            "discount_type": "percentage",
            "discount_value": 10.0
        }'''

    # Execute PATCH Request (must run before DELETE)
    orders_order_id_PATCH_response = client.send_request(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="PATCH",
        body=orders_order_id_PATCH_request_body,
        headers=headers,
        path_params={"order_id": skyramp.get_response_value(orders_POST_response, "order_id")}
    )
    # Generated Assertions
    assert orders_order_id_PATCH_response.status_code == 200
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "order_id") is not None
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "customer_email") == "updated@mail.com"
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "status") == "confirmed"
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "discount_type") == "percentage"
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "discount_value") == 10.0
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "discount_amount") is not None
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "items.0.order_item_id") is not None
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "items.0.product_id") == 1
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "items.0.quantity") == 3
    # Verify total_amount is recalculated when item quantity changes (qty 2 -> 3)
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "total_amount") != skyramp.get_response_value(orders_POST_response, "total_amount")

    # Execute Request
    orders_order_id_DELETE_response = client.send_request(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="DELETE",
        headers=headers,
        path_params={"order_id": skyramp.get_response_value(orders_POST_response, "order_id")}
    )
    # Generated Assertions
    assert orders_order_id_DELETE_response.status_code == 200


if __name__ == "__main__":
    test_integration()
