# Generated by Skyramp v1.3.16 on 2026-03-31 11:09:58.818537458 +0000 UTC m=+193.635681200
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output orders_patch_new_endpoint_happy_path_integration_test.py \
# 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/backend/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/backend/tests/scenario_orders-patch-new-endpoint-happy-path.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    product_id = "1"

    # Request Body
    products_POST_request_body = r'''{
        "category": "Stuffed Animals",
        "description": "Stuffed monkey plush toy",
        "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
        "in_stock": true,
        "name": "Monkey Soft Toy",
        "price": 14.99
    }'''

    # Execute Request
    products_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/products",
        method="POST",
        body=products_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert products_POST_response.status_code == 201
    assert skyramp.get_response_value(products_POST_response, "product_id") is not None
    assert skyramp.get_response_value(products_POST_response, "name") == "Monkey Soft Toy"
    assert skyramp.get_response_value(products_POST_response, "price") >= 0

    # Request Body
    orders_POST_request_body = r'''{
        "customer_email": "original@example.com",
        "items": [
            {
                "product_id": 1,
                "quantity": 1
            }
        ]
    }'''

    # Execute Request
    orders_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/orders",
        method="POST",
        body=orders_POST_request_body,
        headers=headers,
        data_override={"items.0.product_id": skyramp.get_response_value(products_POST_response, "product_id")}
    )
    # Generated Assertions
    assert orders_POST_response.status_code == 201
    assert skyramp.get_response_value(orders_POST_response, "order_id") is not None
    assert skyramp.get_response_value(orders_POST_response, "customer_email") == "original@example.com"
    assert skyramp.get_response_value(orders_POST_response, "status") == "pending"
    assert skyramp.get_response_value(orders_POST_response, "items.0.product_id") == skyramp.get_response_value(products_POST_response, "product_id")
    assert skyramp.get_response_value(orders_POST_response, "items.0.quantity") == 1
    assert skyramp.get_response_value(orders_POST_response, "total_amount") == skyramp.get_response_value(products_POST_response, "price") * 1

    # Request Body
    orders_orders_PATCH_request_body = r'''{
        "customer_email": "updated@example.com",
        "items": [
            {
                "product_id": 1,
                "quantity": 2
            }
        ],
        "status": "confirmed"
    }'''

    # Execute Request
    orders_orders_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/orders/{order_id}",
        method="PATCH",
        body=orders_orders_PATCH_request_body,
        headers=headers,
        path_params={"order_id": skyramp.get_response_value(orders_POST_response, "order_id")},
        data_override={"items.0.product_id": skyramp.get_response_value(products_POST_response, "product_id")}
    )
    # Generated Assertions
    assert orders_orders_PATCH_response.status_code == 200
    assert skyramp.get_response_value(orders_orders_PATCH_response, "order_id") == skyramp.get_response_value(orders_POST_response, "order_id")
    assert skyramp.get_response_value(orders_orders_PATCH_response, "customer_email") == "updated@example.com"
    assert skyramp.get_response_value(orders_orders_PATCH_response, "status") == "confirmed"
    assert skyramp.get_response_value(orders_orders_PATCH_response, "items.0.product_id") == skyramp.get_response_value(products_POST_response, "product_id")
    assert skyramp.get_response_value(orders_orders_PATCH_response, "items.0.quantity") == 2
    assert skyramp.get_response_value(orders_orders_PATCH_response, "items.1.product_id") is None
    assert skyramp.get_response_value(orders_orders_PATCH_response, "total_amount") == skyramp.get_response_value(products_POST_response, "price") * 2


if __name__ == "__main__":
    test_integration()
