# Generated by Skyramp v1.3.16 on 2026-03-31 11:10:03.81971628 +0000 UTC m=+198.636860082
# Command: skyramp generate contract rest http://localhost:8000/api/v1/orders/{order_id} \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/backend/tests \
# 		--overwrite \
# 		--parent-request-data order_id={"customer_email":"setup@example.com","items":[{"product_id":1,"quantity":1}]} \
# 		--parent-status-code order_id=201 \
# 		--provider \
# 		--request-data {"customer_email":"contract@example.com","status":"confirmed","items":[{"product_id":1,"quantity":1}],"discount_type":"fixed","discount_value":5.0} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/orders/{order_id} PATCH
def test_orders_order_id_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    order_id = 0

    # Request Body
    orders_order_id_PATCH_request_body = r'''{
        "customer_email": "contract@example.com",
        "discount_type": "fixed",
        "discount_value": 5,
        "items": [
            {
                "product_id": 1,
                "quantity": 1
            }
        ],
        "status": "confirmed"
    }'''

    # Expected Response Body
    expected_orders_order_id_PATCH_response_body = r'''{
        "created_at": "2022-01-01T00:00:00",
        "customer_email": "abc@mail.com",
        "items": [
            {
                "order_item_id": 1,
                "product_id": 1,
                "quantity": 2
            }
        ],
        "order_id": 1,
        "status": "pending",
        "total_amount": 19.98,
        "updated_at": "2022-01-01T00:00:00"
    }'''

    # Execute Request
    orders_order_id_PATCH_response = client.send_request(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="PATCH",
        body=orders_order_id_PATCH_request_body,
        headers=headers,
        path_params={"order_id": order_id}
    )

    # Generated Assertions
    assert orders_order_id_PATCH_response.status_code == 200
    assert skyramp.check_schema(orders_order_id_PATCH_response, expected_orders_order_id_PATCH_response_body)
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "created_at") is not None
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "customer_email") is not None
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "items.0.order_item_id") is not None
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "order_id") is not None
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "customer_email") == "contract@example.com"
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "status") == "confirmed"
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "total_amount") >= 0
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "items.0.product_id") == 1
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "items.0.quantity") == 1
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "items.1.product_id") is None
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "discount_type") == "fixed"
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "discount_value") == 5.0
    assert skyramp.get_response_value(orders_order_id_PATCH_response, "discount_amount") == 5.0


if __name__ == "__main__":
    test_orders_order_id_patch()
