// Generated by Skyramp v1.3.16 on 2026-03-29 02:27:20.007079123 +0000 UTC m=+168.131614403
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output add_product_image_upload_form.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/add_product_image_upload_form_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(92000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.goto("http://localhost:5173/products");
    await page.getByRole("button", { name: "Add Product" }).click();

    const playwrightRequest0: Record<string, any> = {
        "category": "Electronics",
        "description": "A test product for image upload validation",
        "name": "Test Product Upload",
        "price": 299
    };

    await page.getByTestId("new_product_name").fill(getValue(playwrightRequest0, "name"));
    await page.getByTestId("new_product_description").fill(getValue(playwrightRequest0, "description"));
    await page.getByTestId("new_product_category").fill(getValue(playwrightRequest0, "category"));
    await page.getByRole("combobox").click();
    await page.getByTestId("new_product_instock_yes").click();
    await page.getByTestId("new_product_price").fill(getValue(playwrightRequest0, "price").toString());
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/products**");
    await page.getByRole("button", { name: "Submit" }).click();
    const response0 = await responsePromise0;
});
