// Generated by Skyramp v1.3.16 on 2026-03-29 00:47:29.224999756 +0000 UTC m=+161.266407769
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cancel_order_modal.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/cancel_order_modal_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("navbar-orders").click();
    await page.getByTestId("order-klm@mail.com - 2 items").getByTestId("order-view-details-btn").click();
    await page.getByTestId("cancel-order-trigger").click();
});
