// Generated by Skyramp v1.3.16 on 2026-03-29 00:53:47.54147979 +0000 UTC m=+135.333490843
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output duplicate_warning.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/duplicate_warning_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(81000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("navbar-orders").click();
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").fill("test@example.com");
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Apple MacBook Air").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Apple MacBook Air").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
});
