// Generated by Skyramp v1.3.16 on 2026-03-29 00:54:07.970663538 +0000 UTC m=+155.762674581
// Command: skyramp generate e2e rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output e2e_order_product_flow.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/public/traces/e2e_test_playwright.zip \
// 		--runtime local \
// 		--trace /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/public/traces/e2e_test_trace.json

// Import of required libraries
import { test } from '@playwright/test';
import { SkyrampClient, expect, getBaseUrl, getValue, getResponseValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
let URL_demoshop = getBaseUrl("SKYRAMP_TEST_BASE_URL", "https://demoshop.skyramp.dev");

test('testE2E', async ({ page }) => {
    test.setTimeout(263000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    await page.goto("https://demoshop.skyramp.dev/products");
    await page.getByRole("button", { name: "Edit Session ID" }).click();
    await page.getByRole("textbox").click();
    await page.getByRole("textbox").fill("softly-savepopular");
    await page.getByRole("textbox").press("ArrowUp");
    await page.getByRole("textbox").fill("popular");
    await page.getByRole("textbox").press("ArrowDown");
    await page.getByRole("textbox").fill("skyramp-e2e-demo");
    await page.getByRole("button", { name: "Save Session ID" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/reset**");
    await page.getByTestId("navbar-clear-state").click();
    const response0 = await responsePromise0;

    await page.getByRole("button", { name: "Copy Session ID" }).click();
    // Request Body
    const productsPostRequestBody: string = `{
        "category": "Tablets",
        "description": "High-performance tablet powered by Skyramp",
        "image_url": "https://shorturl.at/sZeO8",
        "in_stock": true,
        "name": "SkyPad Pro",
        "price": 999.99
    }`;

    // Execute Request
    const productsPostResponse = await client.sendRequest({
        url: URL_demoshop,
        path: "/api/v1/products",
        method: "POST",
        body: productsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(productsPostResponse.statusCode, 'status code').toBe(201);
    await page.goto("https://demoshop.skyramp.dev/products");
    await page.getByTestId("product-SkyPad-Pro-view-details").click();
    await page.getByTestId("product-detail-root").click();
    await page.getByRole("button", { name: "Edit Product" }).click();
    await page.getByTestId("product-detail-input-price").click();
    await page.getByTestId("product-detail-input-price").press("ArrowLeft");
    await page.getByTestId("product-detail-input-price").press("ArrowLeft");
    await page.getByTestId("product-detail-input-price").press("ArrowLeft");
    await page.getByTestId("product-detail-input-price").press("ArrowLeft");
    await page.getByTestId("product-detail-input-price").press("ArrowLeft");
    await page.getByTestId("product-detail-input-price").press("ArrowLeft");

    const playwrightRequest0: Record<string, any> = {"price": 1999.99};

    await page.getByTestId("product-detail-input-price").fill(getValue(playwrightRequest0, "price").toString());
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/products/**");
    await page.getByRole("button", { name: "Save Product" }).click();
    const response1 = await responsePromise1;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Request Body
    const ordersPostRequestBody: string = `{
        "customer_email": "sahil@skyramp.dev",
        "items": [
            {
                "product_id": 24,
                "quantity": 2
            }
        ]
    }`;

    // Execute Request
    const ordersPostResponse = await client.sendRequest({
        url: URL_demoshop,
        path: "/api/v1/orders",
        method: "POST",
        body: ordersPostRequestBody,
        headers: headers,
        dataOverride: {"items.0.product_id": getResponseValue(productsPostResponse, "product_id")}
    });

    // Generated Assertions
    expect(ordersPostResponse.statusCode, 'status code').toBe(201);
    await page.getByTestId("navbar-orders").click();
    await page.getByTestId("order-sahil@skyramp.dev - 1 items").getByTestId("order-view-details-btn").click();
    await expect(page.getByTestId("order-detail-value-total")).toContainText("$3999.98");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/v1/orders/**");
    await page.getByRole("button", { name: "Cancel Order" }).click();
    const response2 = await responsePromise2;

    await page.getByTestId("navbar-products").click();
    await page.getByTestId("product-SkyPad-Pro-view-details").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise3 = page.waitForResponse("**/api/v1/products/**");
    await page.getByRole("button", { name: "Delete Product" }).click();
    const response3 = await responsePromise3;
});
