// Generated by Skyramp v1.3.16 on 2026-03-31 09:21:43.435221965 +0000 UTC m=+584.784064975
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output edit_order_form.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/.skyramp/edit_order_form_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(192000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173/orders");
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").click();

    const playwrightRequest0: Record<string, any> = {"customer_email": "test@example.com"};

    await page.getByTestId("add-order-input-email").fill(getValue(playwrightRequest0, "customer_email"));
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Adidas Running Shoes").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/orders**");
    await page.getByTestId("add-order-form-fields-container").getByRole("button", { name: "Add Order" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByTestId("order-detail-edit-btn").click();
    const url0 = `http://localhost:5173/orders/${getValue(await response0.text(), "order_id")}`;
    await page.goto(url0);
    await expect(page.getByTestId("order-detail-heading")).toContainText("Order Details");

    // Register page error listener BEFORE clicking Edit Order so that rendering
    // crashes (e.g. <SelectItem value=""> in EditOrderForm) are captured.
    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.getByTestId("order-detail-edit-btn").click();

    // The EditOrderForm modal should render with its heading visible.
    // This assertion will FAIL due to the rendering crash caused by
    // <SelectItem value=""> in DISCOUNT_TYPES — Radix UI requires non-empty values.
    await expect(page.getByTestId("edit-order-heading")).toBeVisible();

    // Assert no JS page errors occurred during modal render.
    // This will FAIL with: "A <Select.Item /> must have a value prop that is not an empty string"
    expect(pageErrors).toHaveLength(0);
});
