// Generated by Skyramp v1.3.16 on 2026-03-31 10:27:53.031851915 +0000 UTC m=+472.999090117
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output edit_order_form.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/.skyramp/edit_order_form_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(187000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173/orders");
    await page.getByTestId("add-order-btn").click();

    const playwrightRequest0: Record<string, any> = {"customer_email": "test@mail.com"};

    await page.getByTestId("add-order-input-email").fill(getValue(playwrightRequest0, "customer_email"));
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Adidas Running Shoes").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/orders**");
    await page.getByTestId("add-order-form-fields-container").getByRole("button", { name: "Add Order" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("order-detail-heading")).toContainText("Order Details");
    await page.getByTestId("order-detail-edit-btn").click();
    await expect(page.getByTestId("edit-order-heading")).toContainText("Edit Order");
    await page.getByTestId("edit-order-select-status-trigger").click();
    await page.getByTestId("edit-order-status-option-confirmed").click();
    await page.getByTestId("edit-order-select-discount-type-trigger").click();
    await page.getByTestId("edit-order-discount-type-percentage").click();

    const playwrightRequest1: Record<string, any> = {"discount_value": 10};

    await page.getByTestId("edit-order-discount-value-input").fill(getValue(playwrightRequest1, "discount_value").toString());
    await expect(page.getByTestId("edit-order-discount-value-input")).toHaveValue("10");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/orders/**");
    await page.getByTestId("edit-order-submit-btn").click();
    const response1 = await responsePromise1;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("order-detail-value-status")).toContainText("Confirmed");
    await expect(page.getByTestId("order-detail-value-net-total")).toContainText("$116.99");
});
