// Generated by Skyramp v1.3.16 on 2026-03-31 06:04:36.838674819 +0000 UTC m=+404.234172600
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output edit_order_form.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/.skyramp/edit_order_form_trace.zip

// Import of required libraries
import { test, expect } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page);

    await skyrampPage.goto("http://localhost:5173/orders");
    await page.waitForLoadState('networkidle');
    await expect(page.locator('h1')).toBeVisible();

    await skyrampPage.goto("http://localhost:5173/orders/12/edit");
    await page.waitForLoadState('networkidle');
    await expect(page.locator('[data-testid="edit-order-heading"]')).toBeVisible();
    expect(errors).toHaveLength(0);
});
