// Generated by Skyramp v1.3.16 on 2026-03-31 10:02:14.300788027 +0000 UTC m=+667.352600373
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output edit_order_form_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/.skyramp/edit_order_form_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(464000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:5173/orders");
    // Wait for network activities to finish
    await page.waitForLoadState('networkidle');

    await page.goto("http://localhost:5173/orders/1");
    await page.getByTestId("order-detail-edit-btn").click();
    await page.goto("http://localhost:5173/orders/1");
    await expect(page.getByTestId("order-detail-heading")).toContainText("Order Details");
    await page.getByTestId("order-detail-edit-btn").click();
    // Assert the EditOrderForm heading is visible after clicking Edit Order.
    // This assertion FAILS due to <SelectItem value=""> rendering crash in EditOrderForm.tsx
    await expect(page.getByTestId("edit-order-heading")).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
