// Generated by Skyramp v1.3.16 on 2026-03-31 06:01:25.200052466 +0000 UTC m=+411.976354051
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output edit_order_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/.skyramp/edit_order_ui_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(145000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:5173/orders");
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="order-view-details-btn"]').first().waitFor({ state: 'visible', timeout: 10000 });
    await page.locator('[data-testid="order-view-details-btn"]').first().click();
    await expect(page.getByTestId("order-detail-heading")).toContainText("Order Details");
    await page.getByTestId("order-detail-edit-button").click();
    await page.waitForLoadState('networkidle');
    await expect(page.getByTestId("edit-order-heading")).toContainText("Edit Order");
    await expect(page.getByTestId("edit-order-email-input")).toHaveValue("klm@mail.com");
    await expect(page.getByText("$849.98")).toContainText("$849.98");
    await page.getByTestId("edit-order-discount-type-select").click();
    await page.getByRole("option", { name: "Percentage" }).click();
    await expect(page.getByTestId("edit-order-discount-value-input")).toHaveValue("0");
    expect(errors).toHaveLength(0);
});
