// Generated by Skyramp v1.3.16 on 2026-03-31 11:13:55.467941885 +0000 UTC m=+430.285085627
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_edit_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/.skyramp/order_edit_ui_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(93000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173/orders");
    await page.getByTestId("add-order-btn").click();

    const playwrightRequest0: Record<string, any> = {"customer_email": "test@example.com"};

    await page.getByTestId("add-order-input-email").fill(getValue(playwrightRequest0, "customer_email"));
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Adidas Running Shoes").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/orders**");
    await page.getByTestId("add-order-form-fields-container").getByRole("button", { name: "Add Order" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("order-detail-heading")).toContainText("Order Details");

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.getByTestId("order-detail-edit-btn").click();

    await expect(page.getByTestId("order-detail-edit-form")).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
