// Generated by Skyramp v1.3.16 on 2026-03-31 05:41:21.447863543 +0000 UTC m=+423.757794713
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_edit_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/.skyramp/order_edit_ui_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(134000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:5173/orders");
    await page.goto("http://localhost:5173/products");
    await page.goto("http://localhost:5173/orders/1");
    await page.waitForLoadState('networkidle');
    await expect(page.getByTestId("order-detail-heading")).toContainText("Order Details");
    await page.getByTestId("order-detail-edit-btn").click();
    await expect(page.getByTestId("order-detail-edit-form")).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
