// Generated by Skyramp v1.3.16 on 2026-03-31 05:59:35.329166277 +0000 UTC m=+385.623039971
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_detail_edit_mode.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/.skyramp/order_detail_edit_mode_trace.zip

// Import of required libraries
import { test, expect } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    const playwrightPage = page;
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173/orders/1");
    await playwrightPage.waitForLoadState('networkidle');
    await expect(playwrightPage.getByRole('heading', { name: 'Order Details' })).toBeVisible();

    await page.getByTestId("order-detail-edit-btn").click();
    await expect(playwrightPage.getByRole('heading', { name: 'Edit Order' })).toBeVisible();
    expect(errors).toHaveLength(0);
});
