// Generated by Skyramp v1.3.16 on 2026-03-30 23:15:39.18651961 +0000 UTC m=+402.509136132
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_edit_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/.skyramp/order_edit_ui_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(417000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.goto("http://localhost:5173/orders");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto("http://localhost:5173/orders/1");
    await page.getByTestId("order-detail-edit-btn").click();
    await page.goto("http://localhost:5173/orders/1");
    await expect(page.getByTestId("order-detail-heading")).toContainText("Order Details");
    await expect(page.getByTestId("order-detail-value-customer-email")).toContainText("def@mail.com");
    await page.getByTestId("order-detail-edit-btn").click();
});
