// Generated by Skyramp v1.3.16 on 2026-03-30 17:41:11.784866935 +0000 UTC m=+350.635557564
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_detail_view_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/.skyramp/order_detail_ui_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(138000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.waitForLoadState('networkidle');
    await page.getByTestId("navbar-orders").click();
    await page.getByTestId("order-def@mail.com - 2 items").getByRole("button", { name: "View details for order 1" }).click();
    await page.getByTestId("order-detail-edit-btn").click();
    await page.goto("http://localhost:5173/orders/1");
    await page.waitForLoadState('networkidle');
    await page.getByTestId("order-detail-edit-btn").click();
    await page.goto("http://localhost:5173/orders/1");
    await page.waitForLoadState('networkidle');
    await expect(page.getByTestId("order-detail-heading")).toContainText("Order Details");
    await expect(page.getByTestId("order-detail-value-customer-email")).toContainText("def@mail.com");
    await expect(page.getByTestId("order-detail-value-status")).toContainText("Confirmed");
    await expect(page.getByTestId("order-detail-value-total")).toContainText("$999.98");
});
