// Generated by Skyramp v1.3.16 on 2026-03-29 00:58:15.236050488 +0000 UTC m=+119.146410241
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output price_validation_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/price_validation_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(69000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByRole("button", { name: "Add Product" }).click();
    await page.getByTestId("new_product_name").fill("Test Product");
    await page.getByTestId("new_product_price").dblclick();
});
