// Generated by Skyramp v1.3.16 on 2026-03-29 01:01:04.842598715 +0000 UTC m=+110.571577270
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_search_filter.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/product_search_filter_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(86000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    // Wait for React/framework hydration to complete
    await page.waitForTimeout(1500);
    await page.getByRole("textbox", { name: "Search products..." }).fill("Apple");
    await page.getByRole("combobox").click();
    await page.waitForTimeout(1500);
    await page.getByRole("option", { name: "laptop" }).click();
    await page.getByRole("button", { name: "Clear Filters" }).click();
    await page.getByRole("textbox", { name: "Search products..." }).fill("xyznonexistentproduct999");
});
