// Generated by Skyramp v1.3.16 on 2026-03-30 23:12:13.445042365 +0000 UTC m=+186.004745627
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot-k/demoshop-testbot-k/frontend/public/traces/ui_test_playwright.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(192000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("https://demoshop.skyramp.dev/products");
    await page.getByRole("button", { name: "Add Product" }).click();
    await page.getByTestId("new_product_name").click();

    const playwrightRequest0: Record<string, any> = {
        "category": "Phones",
        "description": "The ultimate smartphone - powered by Skyramp",
        "image_url": "https://images.google.com/skyphone1",
        "name": "SkyPhone 1",
        "price": 999
    };

    await page.getByTestId("new_product_name").fill(getValue(playwrightRequest0, "name"));
    await page.getByTestId("new_product_name").press("Tab");
    await page.getByTestId("new_product_description").fill(getValue(playwrightRequest0, "description"));
    await page.getByTestId("new_product_description").press("Tab");
    await page.getByTestId("new_product_image_url").fill(getValue(playwrightRequest0, "image_url"));
    await page.getByTestId("new_product_image_url").press("Tab");
    await page.getByTestId("new_product_category").fill(getValue(playwrightRequest0, "category"));
    await page.getByTestId("new_product_category").press("Tab");
    await page.getByRole("combobox").press("Tab");
    await page.getByTestId("new_product_price").fill(getValue(playwrightRequest0, "price").toString());
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/products**");
    await page.getByRole("button", { name: "Submit" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("product-detail-value-price")).toContainText("$999");
    await page.getByTestId("navbar-orders").click();
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").click();

    const playwrightRequest1: Record<string, any> = {"customer_email": "sahil@skyramp.dev"};

    await page.getByTestId("add-order-input-email").fill(getValue(playwrightRequest1, "customer_email"));
    await page.getByTestId("add-order-label-products").click();
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-SkyPhone 1").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/orders**");
    await page.getByTestId("add-order-form-fields-container").getByRole("button", { name: "Add Order" }).click();
    const response1 = await responsePromise1;

    const responsePromise2 = page.waitForResponse("**/api/v1/orders/**");
    await page.getByRole("button", { name: "Cancel Order" }).click();
    const response2 = await responsePromise2;

    await page.getByTestId("navbar-products").click();
    await page.getByTestId("product-SkyPhone-1-view-details").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise3 = page.waitForResponse("**/api/v1/products/**");
    await page.getByRole("button", { name: "Delete Product" }).click();
    const response3 = await responsePromise3;
});
