name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yaml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yaml'

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: backend

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Wait for service to be ready
        run: sleep 10

      - name: Fetch openapi
        run: |
          RESULT=$(curl -s -X GET http://localhost:8000/openapi.json || "Curl Failed")
          echo $RESULT | jq .

      - name: Validate API response
        run: curl -I -X GET http://localhost:8000

      - name: Run Skyramp generated tests
        shell: bash
        working-directory: backend
        run: |
          python3 -m pip install skyramp
          python3 -m pip install pytest
          export SKYRAMP_TEST_TOKEN=test-bearer-token
          pytest -vvv tests/python/products_*.py
          pytest -vvv tests/python/reset_contract_test.py

      - name: Stop services
        run: docker compose down

